org: superdoug
app: serverlesstemplate
service: trialservice
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    cors:
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - OPTIONS
      allowedOrigins:
        - http://localhost:3000
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://dev-3nlm70j6.us.auth0.com/
        audience:
          - " https://auth0-jwt-authorizer"

functions:
  trialfunction:
    handler: src/functions/trialfunction.trialfunction
    events:
      - httpApi:
          payload: "2.0"
          method: get
          path: /v1/trialfunction
          authorizer:
            name: jwtAuthorizer
            scopes:
              - read:response

plugins:
  - serverless-mocha
  - serverless-offline
custom:
  serverless-mocha-plugin:
    testTemplate: templates/test-template.ejs
    functionTemplate: templates/function-template.ejs
  serverless-offline:
    httpPort: 3001
package:
  patterns:
    - "!package-lock.json"
    - "!templates/**"
    - "!README.md"
    # may want to remove test files - tbd
