'use strict';

// tests for trialfunction
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('trialfunction', '../../../src/functions/trialfunction.js', 'trialfunction');
const AWS = require('aws-sdk-mock')
const AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)
var assert = require('chai').assert

describe('trialfunction', () => {
  before((done) => {
    done();
  });
  //Auth fails

  //Auth passes
  it('implement tests here', async () => {
    const response = await wrapped.run({});
    assert.equal(response.body.message, 'Trial function executed successfully!');
  });
});
