"use strict"; // tests for pages
// Generated by serverless-mocha-plugin
const mochaPlugin = require("serverless-mocha");
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper(
  "pages",
  "../../../src/functions/pages.js",
  "pages"
);
const AWS = require("aws-sdk-mock");
const AWS_SDK = require("aws-sdk");
AWS.setSDKInstance(AWS_SDK);

describe("pages", () => {
  before((done) => {
    done();
  });
  it("implement tests here", async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
