org: superdoug
app: serverlesstemplate
service: pages
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    authorizers:
      jwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://dev-3nlm70j6.us.auth0.com/
        audience:
          - "DougsPagesAuthorizer"
    cors:
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - OPTIONS
      allowedOrigins:
        - http://localhost:3000
        - https://dougspages.io

functions:
  pages:
    handler: src/functions/pages.pages
    events:
      - httpApi:
          method: get
          path: /v1/pages
          authorizer:
            name: jwtAuthorizer
            scopes:
              - read:response

plugins:
  - serverless-offline
  - serverless-mocha
custom:
  serverless-mocha-plugin:
    testTemplate: ../../../backend/servicetemplate/templates/test-template.ejs
    functionTemplate: ../../../backend/servicetemplate/templates/function-template.ejs
  serverless-offline:
    httpPort: 3001
package:
  patterns:
    - "!package-lock.json"
    - "!templates/**"
    - "!README.md"
    # may want to remove test files - tbd
